---
abstract: 'utility methods for lilypond data'
author:
  - 'Jeremy Mates <jmates@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Music-LilyPondUtil
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Scalar::Util: 0
  Test::Exception: 0
  Test::More: 0
  Try::Tiny: 0
  perl: 5.01
resources:
  homepage: https://github.com/thrig/Music-LilyPondUtil
  license: http://dev.perl.org/licenses/
  repository: https://github.com/thrig/Music-LilyPondUtil
version: 0.54
